# Generated by Django 5.2.5 on 2025-08-18 18:35

import django.db.models.deletion
import propiedades.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=8, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('ph', 'PH'), ('local', 'Local'), ('terreno', 'Terreno'), ('otro', 'Otro')], max_length=20)),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler'), ('temporario', 'Temporario')], max_length=20)),
                ('habitaciones', models.PositiveSmallIntegerField(default=0)),
                ('banos', models.PositiveSmallIntegerField(default=0)),
                ('cochera', models.BooleanField(default=False)),
                ('acepta_mascotas', models.BooleanField(default=False)),
                ('superficie_total', models.PositiveIntegerField(blank=True, help_text='m²', null=True)),
                ('superficie_cubierta', models.PositiveIntegerField(blank=True, help_text='m²', null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='activa', max_length=12)),
                ('direccion', models.CharField(help_text='Ej.: Av. Siempre Viva 742', max_length=255)),
                ('localidad', models.CharField(help_text='Ej.: Quilmes', max_length=120)),
                ('provincia', models.CharField(help_text='Ej.: Buenos Aires', max_length=100)),
                ('pais', models.CharField(default='Argentina', max_length=80)),
                ('localidad_norm', models.CharField(editable=False, max_length=140)),
                ('provincia_norm', models.CharField(editable=False, max_length=120)),
                ('pais_norm', models.CharField(editable=False, max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destacada', models.BooleanField(default=False, help_text='Mostrar en el home (máx. 10).')),
                ('imagen_principal', models.ImageField(upload_to='propiedades/portadas/', validators=[propiedades.validators.validar_imagen])),
                ('search_index', models.TextField(blank=True, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['latitud', 'longitud'], name='propiedades_latitud_d7d2f1_idx'), models.Index(fields=['localidad_norm'], name='propiedades_localid_c5918e_idx'), models.Index(fields=['provincia_norm'], name='propiedades_provinc_4e4c25_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropiedadImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/galeria/', validators=[propiedades.validators.validar_imagen])),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad')),
            ],
        ),
    ]
