# Generated by Django 5.2.5 on 2025-08-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propiedad',
            name='propiedades_latitud_d7d2f1_idx',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='longitud',
        ),
    ]
